### ISSUE TITLE
fastify-api-reference: .d.ts lost .js extensions in 1.62.1, breaking moduleResolution nodenext (regression of #4523)

### ISSUE THREAD

**Issue by MRocholl** [scalar/scalar#9795]
### What happens?

Since `1.62.1`, the declaration files published by `@scalar/fastify-api-reference` use **extensionless relative re-exports**, which ESM resolution rejects under `moduleResolution: node16`/`nodenext`:

```ts
// node_modules/@scalar/fastify-api-reference/dist/index.d.ts
export { default } from './fastifyApiReference';   // ❌ needs ./fastifyApiReference.js
export type { … } from './types';                  // ❌ needs ./types.js

// dist/fastifyApiReference.d.ts
import type { FastifyApiReferenceOptions } from './types';  // ❌
```

The package is `"type": "module"`, so these need explicit extensions. With `skipLibCheck: false`:

```
node_modules/@scalar/fastify-api-reference/dist/index.d.ts(1,25): error TS2834:
  Relative import paths need explicit file extensions in ECMAScript imports when
  '--moduleResolution' is 'node16' or 'nodenext'.
node_modules/@scalar/fastify-api-reference/dist/index.d.ts(2,110): error TS2834: …
```

This is a **regression** — it was reported as #4523 and fixed by #4528 in Feb 2025. I bisected the published tarballs (`dist/index.d.ts`, first line):

| version | emitted specifier | |
|---|---|---|
| 1.25.116 | `'./fastifyApiReference.ts'` | (the #4528 fix) |
| 1.31.0 – **1.62.0** | `'./fastifyApiReference.js'` | ✅ |
| **1.62.1** – 1.63.0 | `'./fastifyApiReference'` | ❌ |

**Last good: `1.62.0` (2026-06-26). First bad: `1.62.1` (2026-06-30).** Latest (`1.63.0`) is still affected.

`1.62.1` is #9539, which replaced `tsc + copy:standalone` with a Vite/Rolldown lib build so the standalone script is inlined (a good fix for a real bug — not disputing the change). The side effect looks like the declaration emit moving to `vite-plugin-dts`, where the previous `tsc-alias` step was what appended `.js`. Contrast a sibling package with the identical `exports` shape, which still emits correctly:

```ts
// @scalar/client-side-rendering@0.3.2/dist/index.d.ts
export { … } from './html-rendering.js'   // ✅
```

Worth noting why CI didn't catch it: #9539's checks (`types:check`, Biome, knip, package tests) all run inside the monorepo under `moduleResolution: bundler`, which tolerates extensionless specifiers. The failure is only observable from a consumer using `node16`/`nodenext`.

**Why it bites even with `skipLibCheck: true`** (the common case, so this is easy to miss): `skipLibCheck` hides the TS2834 diagnostic but does not repair resolution, so the default export degrades to an error type in consumer code. `tsc` then has nothing to say about passing an error/`any` value into a typed parameter — but type-aware linting does:

```ts
import scalarApiReference from '@scalar/fastify-api-reference';

// typescript-eslint / oxlint: no-unsafe-argument
//   "Unsafe argument of type error typed assigned to a parameter of type
//    FastifyPluginCallback<…>"
app.register(scalarApiReference, { routePrefix: '/docs', configuration: { url: '/openapi.json' } });
```

So consumers silently lose all types for the plugin, and anyone running type-aware lint rules gets a hard failure they can only suppress. Runtime is unaffected — #9539's actual goal works fine; this is type-only.

### Reproduction

```bash
npm i @scalar/fastify-api-reference@1.63.0 fastify typescript
# tsconfig: { "module": "NodeNext", "moduleResolution": "NodeNext", "skipLibCheck": false }
npx tsc --noEmit    # → TS2834 in dist/index.d.ts

# and the last good release, for contrast:
npm i @scalar/fastify-api-reference@1.62.0 && npx tsc --noEmit   # clean
```

### What did you expect to happen?

`dist/**/*.d.ts` to emit relative specifiers with explicit `.js` extensions, as `1.62.0` and earlier did, so the package's types resolve under `moduleResolution: node16`/`nodenext`.

Two suggestions:

1. Restore `.js` extensions in the declaration output of the Vite build path (`vite-plugin-dts` can be configured to do this, or re-apply the `tsc-alias` step to the emitted `.d.ts`). #8541 proposed a repo-wide version of this and was closed with *"there's a better approach for sure"* — happy to send a PR scoped to `integrations/fastify` only if you'd prefer that shape. Same class of bug was also just fixed for `@scalar/openapi-types` in #9733.
2. Add a regression guard: a tiny consumer fixture that type-checks against the built package under `moduleResolution: nodenext`. Without one this has now shipped twice (#4523, and again here), and in-repo `bundler` resolution structurally cannot catch it.

Related: #4523, #4528, #5859, #8541, #9733.

### OpenAPI Document

N/A — build/type-level issue, independent of the OpenAPI document.
